### ISSUE TITLE
Storage module failing

### ISSUE THREAD

**Issue by edriwing** [kamilkisiela/graphql-hive#1201]
Hi.

We are encountering an issue on the latest tags.

I've been reinstalling all the stack numerous times but some containers won't start.

My main issue is in the storage container, we've reproduced this error on Mac and Linux.

I am using these envs:

```
DOCKER_REGISTRY="ghcr.io/kamilkisiela/graphql-hive/"
DOCKER_TAG=":22a8e5f7aab40fb5aa76a62b517b8be3aafa21f4"
HIVE_ENCRYPTION_SECRET="randompass1"
HIVE_APP_BASE_URL="http://localhost:8080"
HIVE_EMAIL_FROM="no-reply@graphql-hive.com"
SUPERTOKENS_API_KEY="randompass212345678912345678912354799876984698"
CLICKHOUSE_USER="clickhouse"
CLICKHOUSE_PASSWORD="randompass3"
REDIS_PASSWORD="randompass4"
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="randompass5"
POSTGRES_DB="registry"
MINIO_ROOT_USER="minioadmin"
MINIO_ROOT_PASSWORD="minioadmin"
CDN_AUTH_PRIVATE_KEY=""
```

**This tag works**: 7c84107e9fbbedc8bedb55e9cba6ae95355c994e
**This one does not:** 22a8e5f7aab40fb5aa76a62b517b8be3aafa21f4
**And this other one from 3 hours ago neither:** 0d0570032da3ba3896022a426a9d59fa6c101407

I am getting this error on storage:

```
> @hive/migrations@0.0.0 db:migrator
> node --experimental-specifier-resolution=node --loader ts-node/esm src/index.ts up

(node:19) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
/usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts(2,18): error TS2307: Cannot find module 'node:path' or its corresponding type declarations.
src/index.ts(3,17): error TS2307: Cannot find module 'node:url' or its corresponding type declarations.
src/index.ts(21,19): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(50,5): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(53,5): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(57,43): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(57,68): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(57,85): error TS2580: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

    at createTSError (/usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/esm.ts:400:37)
    at /usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/usr/src/app/node_modules/.pnpm/ts-node@10.9.1_awa2wsr5thmg3i7jqycphctjfq/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  diagnosticCodes: [
    2307, 2307, 2580,
    2580, 2580, 2580,
    2580, 2580
  ]
}
```

I currently reversed to the latest tag I know that worked. Thks for the help

**Comment by dotansimha** [comment]
Hi @edriwing ,
It might be due to a missing env var, I'm trying to locate the exact missing env. 
Can you please try to verify if the storage module has `TS_NODE_TRANSPILE_ONLY=true` set? (using `docker inspect`) 
It's defined on the latest version, but just wanted to make sure it's set correctly on your env https://github.com/kamilkisiela/graphql-hive/blob/main/docker/docker-compose.community.yml#L195

**Comment by edriwing** [comment]
Thks @dotansimha.

Everything is fine now :)

**Comment by dotansimha** [comment]
> Thks @dotansimha.
> 
> Everything is fine now :)

Great! can you share how this was fixed? Because we are considering adding an upgrade section to the self-hosting guide, and mention the `--force-recreate` compose flag.

**Comment by edriwing** [comment]
I edited my message :)
