### ISSUE TITLE
Request body is too large - fastify error.

### ISSUE THREAD

**Issue by tapaderster** [kamilkisiela/graphql-hive#2768]
Started getting `Request body is too large` error from the **_schema_** application.

What's the best place to update the [bodyLimit](https://fastify.dev/docs/latest/Reference/Server/#bodylimit) for the fastify request? or make it configurable?

Using self-hosted graphql hive.
version: `2dca491d7ad8727120c12230cf74826c7a8f5411`
We are using the external composition for federation 2 schema composition.

```
err: {
     code: FST_ERR_CTP_BODY_TOO_LARGE
     message: Request body is too large
     name: FastifyError
     stack: FastifyError: Request body is too large
    at rawBody (file:///usr/src/app/index.js:40358:20)
    at ContentTypeParser.run (file:///usr/src/app/index.js:40329:9)
    at handleRequest (file:///usr/src/app/index.js:23252:43)
    at runPreParsing (file:///usr/src/app/index.js:43926:9)
    at next (file:///usr/src/app/index.js:22949:11)
    at file:///usr/src/app/index.js:53984:16
    at resolveOriginOption (file:///usr/src/app/index.js:53960:134)
    at onRequest (file:///usr/src/app/index.js:53961:7)
    at Object.<anonymous> (file:///usr/src/app/index.js:53914:11)
    at hookIterator (file:///usr/src/app/index.js:23024:14)
     statusCode: 413
     type: FastifyError
   }
```

**Comment by tapaderster** [comment]
Seems like this is being [set](https://github.com/kamilkisiela/graphql-hive/blob/e8062277e58f161907a26ee02766fe8f88358591/packages/services/service-common/src/fastify.ts#L19) to `11mb`. And that makes sense, since our total services artifact exceeded that size.

What's the best way to override that?

**Comment by kamilkisiela** [comment]
I think you can introduce an environment variable with a default that makes sense to you.
I will talk with the team and figure out a good limit for us.
Because it will be an env var, every self-hosted instance can have its own value.

**Comment by tapaderster** [comment]
This issue has been resolved with https://github.com/kamilkisiela/graphql-hive/pull/2770
