### ISSUE TITLE
@graphql-hive/client throws TypeError

### ISSUE THREAD

**Issue by shobhitsharma** [kamilkisiela/graphql-hive#2816]
Stacktrace

```
Failed to collect operation TypeError: Cannot read properties of undefined (reading 'definitions')
    at complete (/node_modules/.pnpm/@graphql-hive+client@0.24.1_graphql@16.6.0/node_modules/@graphql-hive/client/cjs/internal/usage.js:104:57)
    at Object.willSendResponse (/node_modules/.pnpm/@graphql-hive+client@0.24.1_graphql@16.6.0/node_modules/@graphql-hive/client/cjs/apollo.js:155:25)
    at /node_modules/.pnpm/@apollo+server@4.9.3_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/requestPipeline.js:274:75
    at Array.map (<anonymous>)
    at invokeWillSendResponse (/node_modules/.pnpm/@apollo+server@4.9.3_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/requestPipeline.js:274:44)
    at sendErrorResponse (/node_modules/.pnpm/@apollo+server@4.9.3_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/requestPipeline.js:293:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processGraphQLRequest (/node_modules/.pnpm/@apollo+server@4.9.3_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/requestPipeline.js:51:24)
    at async internalExecuteOperation (/node_modules/.pnpm/@apollo+server@4.9.3_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/ApolloServer.js:634:16)
```

**Comment by dotansimha** [comment]
Thanks @shobhitsharma , can you please share more details? what version of this package are you using? and what GraphQL server + NodeJS version are you running?

**Comment by kamilkisiela** [comment]
```
"@apollo/server": "4.9.3"
"@graphql-hive/client": "0.24.1"
"graphql": "16.6.0"
```

**Comment by kamilkisiela** [comment]
I can't reproduce it :(

**Comment by imdadul** [comment]
> Can you try `0.24.2-alpha-20230928151650-fb1f0fa0`? In #2979 I added a log message with an operation name when a `DocumetNode` is not available. It should help us narrow down the issue to a specific GraphQL operation.

```
Failed to collect operation TypeError: Cannot read properties of undefined (reading 'name')
    at Object.Field (/node_modules/.pnpm/@graphql-hive+client@0.24.2-alpha-20230928151650-fb1f0fa0_graphql@16.6.0/node_modules/@graphql-hive/client/cjs/internal/usage.js:253:54)
    at Object.enter (/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/visitor.js:197:21)
    at collect (/node_modules/.pnpm/@graphql-hive+client@0.24.2-alpha-20230928151650-fb1f0fa0_graphql@16.6.0/node_modules/@graphql-hive/client/cjs/internal/usage.js:249:29)
    at /node_modules/.pnpm/@graphql-hive+client@0.24.2-alpha-20230928151650-fb1f0fa0_graphql@16.6.0/node_modules/@graphql-hive/client/cjs/internal/utils.js:38:23
    at complete (/node_modules/.pnpm/@graphql-hive+client@0.24.2-alpha-20230928151650-fb1f0fa0_graphql@16.6.0/node_modules/@graphql-hive/client/cjs/internal/usage.js:122:54)
    at Object.willSendResponse (/node_modules/.pnpm/@graphql-hive+client@0.24.2-alpha-20230928151650-fb1f0fa0_graphql@16.6.0/node_modules/@graphql-hive/client/cjs/apollo.js:171:25)
    at /node_modules/.pnpm/@apollo+server@4.9.3_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/requestPipeline.js:274:75
    at Array.map (<anonymous>)
    at invokeWillSendResponse (/node_modules/.pnpm/@apollo+server@4.9.3_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/requestPipeline.js:274:44)"

```

**Comment by kamilkisiela** [comment]
@imdadul hmm to me it seems like GraphQLSchema is not in sync with GraphQL operation.

Can you try `0.24.3-alpha-20231005085447-ceb7a201`? It should display operation's name and a location of the error (path to a field).
Will you be able to create a reproduction?

**Comment by bozvul993** [comment]
I have this same issue:
```
/node_modules/@graphql-hive/core/cjs/client/collect-schema-coordinates.js:206
    return (0, graphql_1.getNamedType)(inputType).name;
                                                 ^
TypeError: Cannot read properties of undefined (reading 'name')
    at resolveTypeName (/node_modules/@graphql-hive/core/cjs/client/collect-schema-coordinates.js:206:50)
    at collectNode (/node_modules/@graphql-hive/core/cjs/client/collect-schema-coordinates.js:37:34)
    at ObjectField (/node_modules/@graphql-hive/core/cjs/client/collect-schema-coordinates.js:188:13)
    at Object.enter (/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/node_modules/graphql/language/visitor.js:197:21)
    at collectSchemaCoordinates (/node_modules/@graphql-hive/core/cjs/client/collect-schema-coordinates.js:110:25)
    at collect (/node_modules/@graphql-hive/core/cjs/client/usage.js:243:86)
    at /node_modules/@graphql-hive/core/cjs/client/utils.js:72:23
    at async captureAsync (/node_modules/@graphql-hive/core/cjs/client/agent.js:40:21)
```

I seems the call to 

```
const inputType = args.typeInfo.getInputType();
// inside collectNode function
``` 
returns undefined.

I'm using graphql: 16.9.0

**Comment by dotansimha** [comment]
@imdadul Any update? are you still having the issue mentioned above?
