### ISSUE TITLE
Failing configuration of usage reporting with @apollo/server

### ISSUE THREAD

**Issue by evebrnd** [kamilkisiela/graphql-hive#2956]
Hello,

I am currently using Hive GraphQL in a Federation v2 setup with the latest packages of @apollo/server and @apollo/gateway.
I enabled usage reporting with [your configuration suggestions](https://the-guild.dev/graphql/envelop/plugins/use-graphql-hive#apollo-server-example) and I am getting the following error
```
Failed to collect operation TypeError: Cannot read properties of undefined (reading 'headers')
    at Object.clientInfo (/dist/gateways.js:51:46)
    at complete (node_modules/@graphql-hive/client/cjs/internal/usage.js:138:43)
    at Object.willSendResponse (node_modules/@graphql-hive/client/cjs/apollo.js:155:25)
    at node_modules/@apollo/server/dist/cjs/requestPipeline.js:274:75
    at Array.map (<anonymous>)
    at invokeWillSendResponse (node_modules/@apollo/server/dist/cjs/requestPipeline.js:274:44)
    at processGraphQLRequest (@apollo/server/dist/cjs/requestPipeline.js:214:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async internalExecuteOperation (node_modules/@apollo/server/dist/cjs/ApolloServer.js:634:16)
    at async runHttpQuery (@apollo/server/dist/cjs/runHttpQuery.js:135:29)
```

Everything is running with the latest Apollo `startStandaloneServer` and the gateway is instanciated regularly as such :
```
const gateway = new ApolloGateway({
    supergraphSdl: createSupergraphManager({
      endpoint: env().hiveCdnEndpoint,
      key: env().hiveCdnKey,
      pollIntervalInMs: 15_000,
    }),
  });
```

Thanks for your help !

**Comment by n1ru4l** [comment]
Closing due to inactivity.
