### ISSUE TITLE
Error Failed to collect operation

### ISSUE THREAD

**Issue by gilberto1991** [kamilkisiela/graphql-hive#305]
On monitoring keeps given me this error using apollo-server-express with this config on plugins

` hiveApollo({
          enabled: true,
          token: config.get('analytics.token'),
          debug: true,
          usage: true
        })`

    Failed to collect operation RangeError: Maximum call stack size exceeded
  
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:367:38)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)
    at markEntireTypeAsUsed (.../node_modules/@graphql-hive/client/index.js:383:17)`
    
    "@graphql-hive/client": "^0.18.2",
    "apollo-server-express": "^3.0.0",
    "graphql": "^15.5.1",
    "mongodb": "^4.1.2",
    "mongoose": "^6.5.2",
    
    
If you could help me figure out how to solve this problem I would appreciate it.

**Comment by kamilkisiela** [comment]
Is it possible you have a type referencing itself at some level of the query? I think that's what causing the issue. I will add an `if` check to prevent the loop.

**Comment by gilberto1991** [comment]
> Is it possible you have a type referencing itself at some level of the query? I think that's what causing the issue. I will add an `if` check to prevent the loop.

I have find the problem, was in the query filters, enters a loop with AND/OR inside AND/OR options from the filters
Thanks @kamilkisiela

**Comment by kamilkisiela** [comment]
`0.18.3`
