### ISSUE TITLE
Debugging 504 Gateway Time-out

### ISSUE THREAD

**Issue by sachinkariyattin** [kamilkisiela/graphql-hive#4496]
What is the best way to debug GraphQL Error (Code: 504): {"response":{"error":"<html>\r\n<head><title>504 Gateway Time-out</title> ?

I am currently working with an older version (the new version gave the same error as well). Both my server and schema service are up and running. I have also verified by hitting the https://<myservice.com>/graphql endpoint.

If I pass invalid token, I do see errors being logged in the server logs for passing invalid token. But with timeout issue, there are no errors logged.

Facing this when publishing the schema. I am sure something is wrong with my setup but looking for any logs that can point me to the error

``` 
npx hive schema:publish --registry.accessToken xxxxxxxxxxxxxx --registry.endpoint https://<myservice.com>/graphql  --author "xxx" --commit "test commit 0.30"
 ›   Warning: --force is enabled by default for newly created projects
✖ Failed to publish schema
 ›   Error: GraphQL Error (Code: 504): {"response":{"error":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n","status":504,"headers":{}},"request":{"query":"mutation
 ›   schemaPublish($input: SchemaPublishInput!, $usesGitHubApp: Boolean!) {\n  schemaPublish(input: $input) {\n    __typename\n    ... on SchemaPublishSuccess @skip(if: $usesGitHubApp) {\n      initial\n      valid\n      successMessage: message\n      linkToWebsite\n
 ›        changes {\n        nodes {\n          message\n          criticality\n        }\n        total\n      }\n    }\n    ... on SchemaPublishError @skip(if: $usesGitHubApp) {\n      valid\n      linkToWebsite\n      changes {\n        nodes {\n          message\n
 ›            criticality\n        }\n        total\n      }\n      errors {\n        nodes {\n          message\n        }\n        total\n      }\n    }\n    ... on SchemaPublishMissingServiceError @skip(if: $usesGitHubApp) {\n      missingServiceError: message\n
 ›   }\n    ... on SchemaPublishMissingUrlError @skip(if: $usesGitHubApp) {\n      missingUrlError: message\n    }\n    ... on GitHubSchemaPublishSuccess @include(if: $usesGitHubApp) {\n      message\n    }\n    ... on GitHubSchemaPublishError @include(if:
 ›   $usesGitHubApp) {\n      message\n    }\n  }\n}","variables":{"input":{"author":"xxx","commit":"test commit 0.30","sdl":"type Query { hello: String! }","force":false,"experimental_acceptBreakingChanges":false,"github":false},"usesGitHubApp":false}}}
```

In the server logs I see this 

```
Flag "startTransaction" is disabled but Sentry failed to find a transaction.
Try to create a transaction before GraphQL execution phase is started.
{
    "level": 20,
    "time": 1712949569435,
    "pid": 1,
    "hostname": "ip-xxxxxx.ec2.internal",
    "msg": "Fetching token (token=704**************************709) - (requestId=IkikN3CISU6QxmTlrOwS5g/0000000182)"
}
```

There are no other exceptions/errors.

**Comment by kamilkisiela** [comment]
It's not enough information for me to help you solve the issue. Please share also logs from `tokens` service and some information about how you deploy / configure things.

**Comment by sachinkariyattin** [comment]
All the services are up and running successfully based on the logs. I am trying to deploy this in AWS. Below are the logs for tokens service

```
{
    "level": 30,
    "time": 1712866137724,
    "pid": 7,
    "hostname": "ip-10-0-xx-xxx.ec2.internal",
    "msg": "Service \"tokens\" is ready"
}
{
    "level": 30,
    "time": 1712866137725,
    "pid": 7,
    "hostname": "ip-10-0-xx-xx.ec2.internal",
    "msg": "Server listening at http://[::]:8080"
}
2024-04-11T20:08:57.734Z ioredis:redis status[10.0.xxx.111:6379]: connecting -> connect
2024-04-11T20:08:57.734Z ioredis:redis status[10.0.xxx.111:6379]: connect -> ready
{
    "level": 30,
    "time": 1712866137735,
    "pid": 7,
    "hostname": "ip-10-0-xxx-xxx.ec2.internal",
    "msg": "Redis connection established"
}
{
    "level": 30,
    "time": 1712866137735,
    "pid": 7,
    "hostname": "ip-10-0-xxx-xxx.ec2.internal",
    "msg": "Redis is ready, purging the in-memory cache"
}
{
    "level": 30,
    "time": 1712866137735,
    "pid": 7,
    "hostname": "ip-10-0-xxx-xxx.ec2.internal",
    "msg": "Redis connection ready... "
}
```

I dont see any requests being logged in the tokens service though. This was for an older version of Hive. I tried deploying the latest images but encountering a different [error](https://github.com/kamilkisiela/graphql-hive/issues/4520). I have added the logs there as well. Please take a look at that issue as well

**Comment by sachinkariyattin** [comment]
Tried with the latest version of Hive. Here is the error I am seeing in the server logs after the request gets timed out 
**Hive CLI: @graphql-hive/cli/0.34.1 darwin-x64 node-v18.19.1**
```
TRPCClientError: fetch failed
    at TRPCClientError.from (file:///usr/src/app/@hive/server/index.js:283979:12)
    at file:///usr/src/app/@hive/server/index.js:284126:30 {
  message: 'Invalid token provided',
  path: [ 'schemaPublish' ],
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] 
{}
}
TRPCClientError: fetch failed
    at TRPCClientError.from (file:///usr/src/app/@hive/server/index.js:283979:12)
    at file:///usr/src/app/@hive/server/index.js:284126:30 {
  message: 'Invalid token provided',
  path: undefined,
  locations: undefined,
  extensions: [Object: null prototype] 
{}
```

**Comment by sachinkariyattin** [comment]
I was able to resolve this. If you are deploying this using the AWS redis cluster, ensure TLS is disabled by setting this [flag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-transitencryptionenabled) to `false`. 

This [issue](https://github.com/kamilkisiela/graphql-hive/issues/2250) helped me get to the root cause.
