### ISSUE TITLE
 Relation "supertokens_thirdparty_users" does not exist

### ISSUE THREAD

**Issue by sachinkariyattin** [kamilkisiela/graphql-hive#4520]
Hello,

I am trying to self host Hive. I have successfully deployed all the latest images. I am facing an issue when trying to signup/signin. I see the below in the server logs

```
{t: "2024-04-15T23:56:52.983Z", message: "setToken: Setting access token as cookie", file: "file:///usr/src/app/@hive/server/index.js:28596:25" sdkVer: "15.2.1"}
{t: "2024-04-15T23:56:52.983Z", message: "setToken: Setting refresh token as cookie", file: "file:///usr/src/app/@hive/server/index.js:28596:25" sdkVer: "15.2.1"}
{t: "2024-04-15T23:56:52.983Z", message: "createNewSession: Attached new tokens to res", file: "file:///usr/src/app/@hive/server/index.js:28596:25" sdkVer: "15.2.1"}
{t: "2024-04-15T23:56:52.989Z", message: "errorHandler: Started", file: "file:///usr/src/app/@hive/server/index.js:28596:25" sdkVer: "15.2.1"}
{t: "2024-04-15T23:56:52.989Z", message: "errorHandler: Started", file: "file:///usr/src/app/@hive/server/index.js:28596:25" sdkVer: "15.2.1"}
{
    "level": 50,
    "time": 1713225412990,
    "pid": 7,
    "hostname": "ip-10-0-xxx-xxx.ec2.internal",
    "reqId": "req-17a",
    "err": {
        "type": "TRPCError",
        "message": "relation \"supertokens_thirdparty_users\" does not exist: relation \"supertokens_thirdparty_users\" does not exist",
        "stack": "error: relation \"supertokens_thirdparty_users\" does not exist\n    at file:///usr/src/app/@hive/server/index.js:228058:21\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/@hive/server/index.js:221487:24\n    at async executeQuery (file:///usr/src/app/@hive/server/index.js:219523:22)\n    at async query (file:///usr/src/app/@hive/server/index.js:221485:14)\n    at async maybeOne (file:///usr/src/app/@hive/server/index.js:222322:24)\n    at async Object.getUserBySuperTokenId (file:///usr/src/app/@hive/server/index.js:319693:20)\n    at async file:///usr/src/app/@hive/server/index.js:319853:28\n    at async execTransaction (file:///usr/src/app/@hive/server/index.js:224233:24)\n    at async transaction (file:///usr/src/app/@hive/server/index.js:224287:16)\n    at async createConnection (file:///usr/src/app/@hive/server/index.js:224850:18)\n    at async Object.transaction (file:///usr/src/app/@hive/server/index.js:224539:18)\n    at async file:///usr/src/app/@hive/server/index.js:319415:14\n    at async file:///usr/src/app/@hive/server/index.js:343897:20\n    at async resolveMiddleware (file:///usr/src/app/@hive/server/index.js:302126:22)\n    at async callRecursive (file:///usr/src/app/@hive/server/index.js:302154:25)\ncaused by: error: relation \"supertokens_thirdparty_users\" does not exist\n    at file:///usr/src/app/@hive/server/index.js:228058:21\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/@hive/server/index.js:221487:24\n    at async executeQuery (file:///usr/src/app/@hive/server/index.js:219523:22)\n    at async query (file:///usr/src/app/@hive/server/index.js:221485:14)\n    at async maybeOne (file:///usr/src/app/@hive/server/index.js:222322:24)\n    at async Object.getUserBySuperTokenId (file:///usr/src/app/@hive/server/index.js:319693:20)\n    at async file:///usr/src/app/@hive/server/index.js:319853:28\n    at async execTransaction (file:///usr/src/app/@hive/server/index.js:224233:24)\n    at async transaction (file:///usr/src/app/@hive/server/index.js:224287:16)\n    at async createConnection (file:///usr/src/app/@hive/server/index.js:224850:18)\n    at async Object.transaction (file:///usr/src/app/@hive/server/index.js:224539:18)\n    at async file:///usr/src/app/@hive/server/index.js:319415:14\n    at async file:///usr/src/app/@hive/server/index.js:343897:20\n    at async resolveMiddleware (file:///usr/src/app/@hive/server/index.js:302126:22)\n    at async callRecursive (file:///usr/src/app/@hive/server/index.js:302154:25)",
        "code": "INTERNAL_SERVER_ERROR",
        "name": "TRPCError"
    },
    "msg": "relation \"supertokens_thirdparty_users\" does not exist"
}
{
    "level": 40,
    "time": 1713225412991,
    "pid": 7,
    "hostname": "ip-10-0-xxx-xxx.ec2.internal",
    "reqId": "req-17a",
    "msg": "Replying with 500 Internal Server Error"
}
```

I was previously running the older version of Hive setup. Started seeing this when I deployed the new version. Could you please let me know how to fix this? The older version was also a test up and I am ok to cleanup any data if required.

**Comment by sachinkariyattin** [comment]
@kamilkisiela @n1ru4l Could you please review this and provide any directions? I tried deleting the previous setup and redeploying again. Still not able to resolve this. 

I am self hosting this on AWS and all the containers are up. This is happening for the latest images. Works fine when I spin up the images locally.

**Comment by sachinkariyattin** [comment]
I have narrowed it down to this 

```

Loading supertokens config.
Completed config.yaml loading.
Loading storage layer.
Using in memory storage.
Loading supertokens version.yaml file.
```

Supertokens seems to be using an in memory storage even after passing all the env variables for POSTGRES

**Comment by sachinkariyattin** [comment]
I was passing `POSTGRES_` instead of `POSTGRESQL_` for env variables. I will close this issue
