### ISSUE TITLE
Unable to successfully launch GraphQL Hive with self-hosting instructions

### ISSUE THREAD

**Issue by Tohaker** [kamilkisiela/graphql-hive#491]
First of all, I wanted to say how much I appreciate the Docker Compose file you've put together. 

I've been following the instructions at https://docs.graphql-hive.com/self-hosting/get-started and found that, once I give supertokens an API key longer than 20 characters (this also needs updating in your docs) and sign up/in, I'm always greeted with the following screen;

![image](https://user-images.githubusercontent.com/33665681/196054887-4e2f7be2-ccb6-4b29-9751-79cd810247cc.png)

At the same time, a big red error is thrown in the server container. Here's the full log

```
[hive] is not enabled.
{"level":30,"time":1665948830035,"pid":1,"hostname":"67e225610f13","msg":"Service \"graphql-api\" is ready"}
{"level":30,"time":1665948830037,"pid":1,"hostname":"67e225610f13","msg":"Server listening at http://0.0.0.0:3001"}
{"level":20,"time":1665948830039,"pid":1,"hostname":"67e225610f13","msg":"Redis connection established"}
{"level":30,"time":1665948830040,"pid":1,"hostname":"67e225610f13","msg":"Redis connection ready"}
{"level":20,"time":1665948847104,"pid":1,"hostname":"67e225610f13","msg":"Running idempotent job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"level":20,"time":1665948847104,"pid":1,"hostname":"67e225610f13","msg":"Starting new job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"level":20,"time":1665948847109,"pid":1,"hostname":"67e225610f13","msg":"Fetching organizations - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"level":20,"time":1665948847110,"pid":1,"hostname":"67e225610f13","msg":"Running idempotent job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"level":20,"time":1665948847110,"pid":1,"hostname":"67e225610f13","msg":"Starting new job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"level":20,"time":1665948847110,"pid":1,"hostname":"67e225610f13","msg":"Job not found (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"level":20,"time":1665948847110,"pid":1,"hostname":"67e225610f13","msg":"Trying to create a job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"level":20,"time":1665948847111,"pid":1,"hostname":"67e225610f13","msg":"Job not found (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"level":20,"time":1665948847111,"pid":1,"hostname":"67e225610f13","msg":"Trying to create a job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"level":20,"time":1665948847123,"pid":1,"hostname":"67e225610f13","msg":"Job is pending (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"level":20,"time":1665948847123,"pid":1,"hostname":"67e225610f13","msg":"Starting new job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3, attempt=2) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"level":20,"time":1665948847124,"pid":1,"hostname":"67e225610f13","msg":"Job created (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"level":20,"time":1665948847124,"pid":1,"hostname":"67e225610f13","msg":"Executing job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"level":20,"time":1665948847126,"pid":1,"hostname":"67e225610f13","msg":"Awaiting job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3, time=0) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","logLevel":20,"stats":{"idleConnectionCount":0,"totalConnectionCount":1,"waitingRequestCount":0}},"message":"created a new client connection","sequence":"0","time":1665948847185,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","logLevel":20,"stats":{"idleConnectionCount":0,"totalConnectionCount":1,"waitingRequestCount":0}},"message":"client is checked out from the pool","sequence":"1","time":1665948847186,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","connectionId":"Yt6aBGjkQMq4bQkC5tUtRA-1","queryId":"Yt6aBGjkQMq4bQkC5tUtRA-2","logLevel":20,"sql":"\n        SELECT\n          *\n        FROM\n          public.\"users\"\n        WHERE\n          \"supertoken_user_id\" = $1\n        LIMIT 1\n      ","values":["676c4f3b-00a5-4587-b754-e85355510037"]},"message":"executing query","sequence":"2","time":1665948847187,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","connectionId":"Yt6aBGjkQMq4bQkC5tUtRA-1","queryId":"Yt6aBGjkQMq4bQkC5tUtRA-2","logLevel":20,"executionTime":"22ms","rowCount":null},"message":"query execution result","sequence":"3","time":1665948847211,"version":"2.0.0"}
{"level":30,"time":1665948847213,"pid":1,"hostname":"67e225610f13","msg":"Creating new user (input={\"superTokensUserId\":\"676c4f3b-00a5-4587-b754-e85355510037\",\"externalAuthUserId\":null,\"email\":\"milesbardon@gmail.com\"}) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","logLevel":20,"stats":{"idleConnectionCount":0,"totalConnectionCount":1,"waitingRequestCount":0}},"message":"client is checked out from the pool","sequence":"4","time":1665948847215,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","connectionId":"Yt6aBGjkQMq4bQkC5tUtRA-3","queryId":"Yt6aBGjkQMq4bQkC5tUtRA-4","logLevel":20,"sql":"\n            INSERT INTO public.users\n              (\"email\", \"supertoken_user_id\", \"full_name\", \"display_name\", \"external_auth_user_id\")\n            VALUES\n              ($1, $2, $3, $4, $5)\n            RETURNING *\n          ","values":["milesbardon@gmail.com","676c4f3b-00a5-4587-b754-e85355510037","milesbardon","milesbardon",null]},"message":"executing query","sequence":"5","time":1665948847216,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","connectionId":"Yt6aBGjkQMq4bQkC5tUtRA-3","queryId":"Yt6aBGjkQMq4bQkC5tUtRA-4","logLevel":20,"executionTime":"18ms","rowCount":1},"message":"query execution result","sequence":"6","time":1665948847234,"version":"2.0.0"}
{"level":20,"time":1665948847235,"pid":1,"hostname":"67e225610f13","msg":"Marking job as completed (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7, attempt=1) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
{"level":20,"time":1665948847236,"pid":1,"hostname":"67e225610f13","msg":"Job completed (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=baf81cc3d30a7) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000000)"}
Flag "startTransaction" is enabled but Sentry failed to find a transaction.
Try to create a transaction before GraphQL execution phase is started.
Flag "startTransaction" is enabled but Sentry failed to find a transaction.
Try to create a transaction before GraphQL execution phase is started.
❌   🧘 Yoga -   NotFoundError: Resource not found.
    at many (file:///usr/src/app/index.js:151706:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createConnection (file:///usr/src/app/index.js:154218:18)
    at async Object.getOrganizations (file:///usr/src/app/index.js:204124:23)
    at async Promise.all (index 0)
    at async file:///usr/src/app/index.js:205917:17
    at async YogaServer.getResultForParams (file:///usr/src/app/index.js:208740:18)
    at async YogaServer.getResponse (file:///usr/src/app/index.js:208804:16)
    at async YogaServer.handle (file:///usr/src/app/index.js:208517:26)
    at async file:///usr/src/app/index.js:210566:24 {
  path: [ 'organizations' ],
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] {}
} 
{"level":20,"time":1665948847629,"pid":1,"hostname":"67e225610f13","msg":"Resolving the job (id=user:create:676c4f3b-00a5-4587-b754-e85355510037, traceId=9113001d92cc3, attempt=2, status=COMPLETED) - (requestId=vJKdugLgQIqwQlRORDfgaA/0000000001)"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","logLevel":20,"stats":{"idleConnectionCount":0,"totalConnectionCount":1,"waitingRequestCount":0}},"message":"client is checked out from the pool","sequence":"7","time":1665948847630,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","connectionId":"Yt6aBGjkQMq4bQkC5tUtRA-5","queryId":"Yt6aBGjkQMq4bQkC5tUtRA-6","logLevel":20,"sql":"\n          SELECT o.*\n          FROM public.organizations as o\n          LEFT JOIN public.organization_member as om ON (om.organization_id = o.id)\n          WHERE om.user_id = $1\n          ORDER BY o.created_at DESC\n        ","values":["64980911-0d2d-40cc-9f0f-5b3327b52d4b"]},"message":"executing query","sequence":"8","time":1665948847632,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","connectionId":"Yt6aBGjkQMq4bQkC5tUtRA-5","queryId":"Yt6aBGjkQMq4bQkC5tUtRA-6","logLevel":20,"executionTime":"30ms","rowCount":null},"message":"query execution result","sequence":"9","time":1665948847662,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","connectionId":"Yt6aBGjkQMq4bQkC5tUtRA-5","logLevel":50,"queryId":"Yt6aBGjkQMq4bQkC5tUtRA-6"},"message":"NotFoundError","sequence":"10","time":1665948847662,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"Yt6aBGjkQMq4bQkC5tUtRA-0","logLevel":20,"stats":{"idleConnectionCount":0,"totalConnectionCount":0,"waitingRequestCount":0}},"message":"client connection is closed and removed from the client pool","sequence":"11","time":1665948847663,"version":"2.0.0"}
```

Would you be able to help me understand where I've gone wrong? The docker-compose config is exactly as specified in your documentation, without any changes (after running the `config` command to inject the env variables)

**Comment by n1ru4l** [comment]
@Tohaker Does the SueprTokens instance output some kind of error message?

**Comment by Tohaker** [comment]
SuperTokens seems fine

```
Loading supertokens config.
Completed config.yaml loading.
Loading storage layer.
Loading PostgreSQL config.
Loading supertokens version.yaml file.
17 Oct 2022 09:37:23:485 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.storage.postgresql.ConnectionPool.initPool(ConnectionPool.java:130) | Setting up PostgreSQL connection pool.

Setting up PostgreSQL connection pool.
17 Oct 2022 09:37:26:147 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:33) | Starting task: RemoveOldSessions

17 Oct 2022 09:37:26:150 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:33) | Starting task: RemoveOldPasswordResetTokens

17 Oct 2022 09:37:26:157 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:33) | Starting task: RemoveOldEmailVerificationTokens

17 Oct 2022 09:37:26:158 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:33) | Starting task: DeleteExpiredPasswordlessDevices

17 Oct 2022 09:37:26:162 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:33) | Starting task: Telemetry

17 Oct 2022 09:37:26:164 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.cronjobs.CronTask.<init>(CronTask.java:33) | Starting task: DeleteExpiredAccessTokenSigningKeys

17 Oct 2022 09:37:26:163 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [pool-1-thread-1] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:43) | Cronjob started: Telemetry

17 Oct 2022 09:37:26:835 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [main] thread | io.supertokens.Main.init(Main.java:219) | Started SuperTokens on 0.0.0.0:3567 with PID: 37

Started SuperTokens on 0.0.0.0:3567 with PID: 37
17 Oct 2022 09:37:27:683 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [pool-1-thread-1] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:52) | Cronjob finished: Telemetry

17 Oct 2022 09:37:58:633 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:163) | API called: /apiversion. Method: GET

17 Oct 2022 09:37:58:636 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /apiversion. Method: GET

17 Oct 2022 09:37:58:654 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-2] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /telemetry. Method: GET. Version: 2.15

17 Oct 2022 09:37:58:659 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-2] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /telemetry. Method: GET

17 Oct 2022 09:38:02:309 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-3] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user. Method: GET. Version: 2.15

17 Oct 2022 09:38:02:322 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-3] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user. Method: GET

17 Oct 2022 09:38:02:329 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-4] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/users/by-email. Method: GET. Version: 2.15

17 Oct 2022 09:38:02:362 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-4] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/users/by-email. Method: GET

17 Oct 2022 09:38:04:630 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/signup. Method: POST. Version: 2.15

17 Oct 2022 09:38:04:810 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/signup. Method: POST

17 Oct 2022 09:38:04:816 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-6] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user. Method: GET. Version: 2.15

17 Oct 2022 09:38:04:832 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-6] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user. Method: GET

17 Oct 2022 09:38:04:837 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-7] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user/email/verify. Method: GET. Version: 2.15

17 Oct 2022 09:38:04:844 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-7] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user/email/verify. Method: GET

17 Oct 2022 09:38:04:850 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-8] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user. Method: GET. Version: 2.15

17 Oct 2022 09:38:04:852 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-8] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user. Method: GET

17 Oct 2022 09:38:04:859 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-9] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/handshake. Method: POST. Version: 2.15

17 Oct 2022 09:38:04:861 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-9] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/handshake. Method: POST

17 Oct 2022 09:38:04:868 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-10] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/session. Method: POST. Version: 2.15

17 Oct 2022 09:38:04:916 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-10] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/session. Method: POST

17 Oct 2022 09:38:04:943 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user. Method: GET. Version: 2.15

17 Oct 2022 09:38:04:945 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user. Method: GET

17 Oct 2022 09:38:04:951 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-2] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user/email/verify. Method: GET. Version: 2.15

17 Oct 2022 09:38:04:953 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-2] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user/email/verify. Method: GET

17 Oct 2022 09:38:04:958 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-3] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/session/regenerate. Method: POST. Version: 2.15

17 Oct 2022 09:38:04:978 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-3] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/session/regenerate. Method: POST

17 Oct 2022 09:38:04:990 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-4] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user. Method: GET. Version: 2.15

17 Oct 2022 09:38:04:993 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-4] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user. Method: GET

17 Oct 2022 09:38:05:001 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user/email/verify. Method: GET. Version: 2.15

17 Oct 2022 09:38:05:004 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user/email/verify. Method: GET

17 Oct 2022 09:38:05:011 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-6] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/session/regenerate. Method: POST. Version: 2.15

17 Oct 2022 09:38:05:040 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-6] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/session/regenerate. Method: POST

17 Oct 2022 09:38:05:052 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-7] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user. Method: GET. Version: 2.15

17 Oct 2022 09:38:05:055 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-7] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user. Method: GET

17 Oct 2022 09:38:05:059 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-8] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/user/email/verify. Method: GET. Version: 2.15

17 Oct 2022 09:38:05:060 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-8] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/user/email/verify. Method: GET

17 Oct 2022 09:38:05:065 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-9] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/session/regenerate. Method: POST. Version: 2.15

17 Oct 2022 09:38:05:073 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-9] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/session/regenerate. Method: POST

17 Oct 2022 09:38:05:428 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-10] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/session/verify. Method: POST. Version: 2.16

17 Oct 2022 09:38:05:431 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159) | API called: /recipe/session/verify. Method: POST. Version: 2.16

17 Oct 2022 09:38:05:435 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-10] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/session/verify. Method: POST

17 Oct 2022 09:38:05:437 +0000 | INFO | pid: c5158e68-c2ce-427f-959b-6fc03dcb77d3 | [http-nio-0.0.0.0-3567-exec-1] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:185) | API ended: /recipe/session/verify. Method: POST
```

**Comment by n1ru4l** [comment]
https://github.com/kamilkisiela/graphql-hive/pull/498

**Comment by n1ru4l** [comment]
I noticed that if I comment out the `Header` component from the web app - this error never occurs

**Comment by kamilkisiela** [comment]
#518 should fix it
