### ISSUE TITLE
Schema check throwing error in server and CLI if everything is fine after update to latest

### ISSUE THREAD

**Issue by PlayAnyData** [kamilkisiela/graphql-hive#5607]
Hey,

yesterday, I have done an upgrade to latest hive (self-hosting) (we were ~9 months back). Since then our schema checks and schema publishes fail with: 
```
Failed to check schema
 »   Error: No access (reason: "Authorization token is missing")  
```

The log is showing:
```
Flag "startTransaction" is disabled but Sentry failed to find a transaction.
Try to create a transaction before GraphQL execution phase is started.
{"level":20,"time":1726219430756,"pid":7,"hostname":"server-867dfdf89f-c9dzd","reqId":"req-7u","msg":"Resolving user"}
{"level":20,"time":1726219430756,"pid":7,"hostname":"server-867dfdf89f-c9dzd","reqId":"req-7u","msg":"Session resolution ended successfully"}
{"level":20,"time":1726219430756,"pid":7,"hostname":"server-867dfdf89f-c9dzd","reqId":"req-7u","msg":"No session found"}
{"level":20,"time":1726219430756,"pid":7,"hostname":"server-867dfdf89f-c9dzd","reqId":"req-7u","msg":"Attempt to resolve an API token from headers"}
{"level":20,"time":1726219430756,"pid":7,"hostname":"server-867dfdf89f-c9dzd","reqId":"req-7u","msg":"Found Authorization header (length=32, token=33f**************************ab7)"}
{"level":20,"time":1726219430757,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching token (token=33f**************************ab7) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":30,"time":1726219430776,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Checking schema (input={\"service\":\"gateway\",\"github\":null,\"meta\":{\"author\":\"***\",\"commit\":\"a00f33ed931eda3e45b1d6f9e30801a2c95b5105\"},\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430776,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching token (token=33f**************************ab7) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching target (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching project (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching organization (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching latest schemas (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching latest schemas (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\",\"onlyComposable\":true}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching maybe latest version (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching organization (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching latest schemas (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching latest schemas (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\",\"onlyComposable\":true}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching maybe latest version (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430782,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching maybe latest valid version (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219430843,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching base schema (selector={\"organization\":\"0dac3370-08f8-4f10-a949-8ba046cb4235\",\"project\":\"ab6b1c11-e38b-4390-86de-51986b2168f1\",\"target\":\"0322d06b-9941-47eb-9de9-6d5b084ec626\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431002,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Executing ClickHouse Query (executionId: getTotalCountForSchemaCoordinates-a979446068cb6):  SELECT SUM(\"result\".\"total\") AS \"amountOfRequests\" FROM ( SELECT SUM(\"operations_daily\".\"total\") AS \"total\" FROM \"operations_daily\" PREWHERE \"operations_daily\".\"target\" IN (['0322d06b-9941-47eb-9de9-6d5b084ec626', '3c71f0f8-c0f8-462d-9535-64afa32e45b3', '84de09df-6771-46e7-ba9b-4a42b65d8339']) AND \"operations_daily\".\"timestamp\" >= toDateTime('2024-08-14 09:23:51', 'UTC') AND \"operations_daily\".\"timestamp\" <= toDateTime('2024-09-13 09:23:51', 'UTC') AND \"operations_daily\".\"client_name\" NOT IN (['integration-tests']) UNION ALL SELECT SUM(\"subscription_operations_daily\".\"total\") AS \"total\" FROM \"subscription_operations_daily\" PREWHERE \"subscription_operations_daily\".\"target\" IN (['0322d06b-9941-47eb-9de9-6d5b084ec626', '3c71f0f8-c0f8-462d-9535-64afa32e45b3', '84de09df-6771-46e7-ba9b-4a42b65d8339']) AND \"subscription_operations_daily\".\"timestamp\" >= toDateTime('2024-08-14 09:23:51', 'UTC') AND \"subscription_operations_daily\".\"timestamp\" <= toDateTime('2024-09-13 09:23:51', 'UTC') AND \"subscription_operations_daily\".\"client_name\" NOT IN (['integration-tests']) ) AS \"result\"  - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431028,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Finished ClickHouse Query (executionId: getTotalCountForSchemaCoordinates-a979446068cb6, duration=26ms) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431028,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Load contract versions for schema version. (schemaVersionId=07eb2984-e21f-4632-849b-6db355d553ab) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431032,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"No contract versions found for schema version. (schemaVersionId=07eb2984-e21f-4632-849b-6db355d553ab) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431032,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Using STITCHING registry model (version=modern) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431032,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Checksum check (existingSchema=yes, existingContractCount=null, incomingContractCount=null) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431298,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Schema is modified. - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431298,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Orchestrator: [object Object] - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431301,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Composing and Validating Stitched Schemas - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431872,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"No validation errors - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431872,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Retrieve previous version SDL. - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431872,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Return pre-computed SDL. - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":30,"time":1726219431872,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Contract checks: null - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431982,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Comparing Schemas - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431999,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Conditional breaking change settings available. - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219431999,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Fetching affected operations and affected clients for breaking changes. - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219432021,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Detected non-breaking changes - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":30,"time":1726219432025,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"diff check status: {\"status\":\"completed\",\"result\":{\"breaking\":null,\"safe\":[{\"id\":\"cd5817edca74ddb2a31e7859647abd14\",\"type\":\"FIELD_ARGUMENT_DESCRIPTION_CHANGED\",\"approvalMetadata\":null,\"criticality\":\"NON_BREAKING\",\"message\":\"Description for argument 'numTypos' on field 'Query.search' changed from 'Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typos.' to 'Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typo.'\",\"meta\":{\"typeName\":\"Query\",\"fieldName\":\"search\",\"argumentName\":\"numTypos\",\"oldDescription\":\"Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typos.\",\"newDescription\":\"Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typo.\"},\"path\":\"Query.search.numTypos\",\"isSafeBasedOnUsage\":false,\"reason\":null,\"usageStatistics\":null,\"breakingChangeSchemaCoordinate\":null}],\"all\":[{\"id\":\"cd5817edca74ddb2a31e7859647abd14\",\"type\":\"FIELD_ARGUMENT_DESCRIPTION_CHANGED\",\"approvalMetadata\":null,\"criticality\":\"NON_BREAKING\",\"message\":\"Description for argument 'numTypos' on field 'Query.search' changed from 'Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typos.' to 'Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typo.'\",\"meta\":{\"typeName\":\"Query\",\"fieldName\":\"search\",\"argumentName\":\"numTypos\",\"oldDescription\":\"Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typos.\",\"newDescription\":\"Number of allowed typos in a field. A single value acts upon all fields, otherwise respects the order of queryBy. Using a negative number defaults this entry. Equivalent to num_typo.\"},\"path\":\"Query.search.numTypos\",\"isSafeBasedOnUsage\":false,\"reason\":null,\"usageStatistics\":null,\"breakingChangeSchemaCoordinate\":null}],\"coordinatesDiff\":{\"added\":{},\"deleted\":{},\"deprecated\":{},\"undeprecated\":{}}}} - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":30,"time":1726219432025,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"policy check status: {\"status\":\"skipped\"} - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219432025,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Schema check successful - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219432028,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Translating Organization Clean ID (selector={\"organization\":\"***\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":20,"time":1726219432028,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Translating Project Clean ID (selector={\"organization\":\"***\",\"project\":\"***\"}) - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
GraphQLError: No access (reason: "Authorization token is missing")
    at new AccessError (file:///usr/src/app/@hive/server/index.js:287289:5)
    at file:///usr/src/app/@hive/server/index.js:289370:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async schemaCheck (file:///usr/src/app/@hive/server/index.js:341795:29)
    at async file:///usr/src/app/@hive/server/index.js:269877:16
    at async YogaServer.getResultForParams (file:///usr/src/app/@hive/server/index.js:275312:18)
    at async handle (file:///usr/src/app/@hive/server/index.js:275388:20)
    at async file:///usr/src/app/@hive/server/index.js:360052:24
    at async Object.<anonymous> (file:///usr/src/app/@hive/server/index.js:360049:5) {
  path: [ 'schemaCheck' ],
{"level":20,"time":1726219432381,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"[useResponseCache] Decided not to cache the response because it contains errors - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
  locations: [ { line: 2, column: 3 } ],
  extensions: { code: 'UNAUTHENTICATED' }
}
AccessError [GraphQLError]: No access (reason: "Authorization token is missing")
    at new AccessError (file:///usr/src/app/@hive/server/index.js:287289:5)
    at file:///usr/src/app/@hive/server/index.js:289370:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async schemaCheck (file:///usr/src/app/@hive/server/index.js:341795:29)
    at async file:///usr/src/app/@hive/server/index.js:269877:16
    at async YogaServer.getResultForParams (file:///usr/src/app/@hive/server/index.js:275312:18)
    at async handle (file:///usr/src/app/@hive/server/index.js:275388:20)
    at async file:///usr/src/app/@hive/server/index.js:360052:24
    at async Object.<anonymous> (file:///usr/src/app/@hive/server/index.js:360049:5) {
  path: undefined,
  locations: undefined,
  extensions: { code: 'UNAUTHENTICATED' }
}
{"level":20,"time":1726219432381,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"Processing GraphQL Parameters done. - (requestId=wpAMOCe9T++6HsFpKZBnkA/0000000164)"}
{"level":30,"time":1726219432382,"pid":7,"hostname":"server-867dfdf89f-c9dzd","msg":"[200] (10.198.34.44) POST /graphql"}
```

I am very confused, as it looks like a schema check is executed. The schema check is also visible in HIVE:
![image](https://github.com/user-attachments/assets/dcf7b106-1526-4038-9f99-a54684de646e)

Do you have any ideas what is causing this? As this is currently breaking our pipelines, as we do schema checks and publishes from cli tool.

Another hint:
If the schema check fails, I get a correct error response:
![image](https://github.com/user-attachments/assets/5670d932-3465-4abd-873f-5083b20195f9)

**Comment by dotansimha** [comment]
@PlayAnyData did you manage to workaround this? maybe with the latest version of Hive? 

Also, what version of the Hive CLI/agent are you using?

**Comment by PlayAnyData** [comment]
@dotansimha Just wanted to upgrade to main, but cannot fetch the manifests anymore, e.g. https://ghcr.io/v2/kamilkisiela/graphql-hive/app/manifests/8b780f9f8e4a77048b7fb09bbc520b37f57d8816 - I get an unauthenticated error.

I will check tomorrow, which version, we are using for CLI. The problem with latest at that point was, that it did not respect self-signed certificates at that point in time and NODE_TLS_REJECT_UNAUTHORIZED was also not taken into account.
