### ISSUE TITLE
[app] SessionError: INVALID_CLAIMS error Status 500 upon login

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#596]
I get the following error when logging in on staging using email + password.

![image](https://user-images.githubusercontent.com/14338007/199933971-5cd48bf6-8b82-4761-b474-dd73278a1f23.png)

Logs from app

```
yarn run v1.22.15
warning package.json: No license field
$ /app/node_modules/.bin/app
started server on localhost:3000, url: http://localhost:3000
SessionError: INVALID_CLAIMS
    at Session.<anonymous> (/app/node_modules/supertokens-node/lib/build/recipe/session/sessionClass.js:146:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/supertokens-node/lib/build/recipe/session/sessionClass.js:15:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'INVALID_CLAIMS',
  payload: [ { id: 'st-ev', reason: [Object] } ],
  errMagic: 'ndskajfasndlfkj435234krjdsa',
  fromRecipe: 'session'
}
```

**Comment by n1ru4l** [comment]
Figured out the root cause - it is an edge case when you registered before but did not confirm your email - or turn on email verification via the `AUTH_REQUIRE_EMAIL_VERIFICATION` flag.

This will be solved via https://github.com/kamilkisiela/graphql-hive/pull/597
