### ISSUE TITLE
storage-broker-1 exited with code 1

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#729]
```
storage-broker-1                | [2022-12-02 08:04:14,906] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
storage-broker-1                | org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
storage-broker-1                |       at org.apache.zookeeper.KeeperException.create(KeeperException.java:126)
storage-broker-1                |       at kafka.zk.KafkaZkClient$CheckedEphemeral.getAfterNodeExists(KafkaZkClient.scala:1903)
storage-broker-1                |       at kafka.zk.KafkaZkClient$CheckedEphemeral.create(KafkaZkClient.scala:1841)
storage-broker-1                |       at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1808)
storage-broker-1                |       at kafka.zk.KafkaZkClient.registerBroker(KafkaZkClient.scala:96)
storage-broker-1                |       at kafka.server.KafkaServer.startup(KafkaServer.scala:335)
storage-broker-1                |       at kafka.Kafka$.main(Kafka.scala:109)
storage-broker-1                |       at kafka.Kafka.main(Kafka.scala)
storage-broker-1                | [2022-12-02 08:04:14,907] INFO [KafkaServer id=1] shutting down (kafka.server.KafkaServer)
storage-broker-1 exited with code 1
```

**Comment by kamilkisiela** [comment]
**Solution**
Delete `broker` and `zookeeper` directories in `packages/services/storage/volumes`
